"""Generator: writes ingest_corpus.py with correct encoding."""
import pathlib

OUT = pathlib.Path(__file__).parent / "ingest_corpus.py"

LINES = [
    '"""',
    'Ingestao do Corpus Dehoniano no Pinecone.',
    'Uso:',
    '  python scripts/ingest_corpus.py',
    '  python scripts/ingest_corpus.py --limit 200 --filter COR',
    '  python scripts/ingest_corpus.py --skip 5000',
    '"""',
    'import os, sys, json, glob, re, argparse, time',
    'from pathlib import Path',
    'from typing import Optional',
    'sys.path.insert(0, str(Path(__file__).parent.parent))',
    'from dotenv import load_dotenv',
    'load_dotenv()',
    'from pinecone import Pinecone',
    'from sentence_transformers import SentenceTransformer',
    '',
    'PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")',
    'INDEX_NAME       = os.getenv("PINECONE_INDEX_NAME", "dehon-ai-index")',
    'CORPUS_DIR       = Path(__file__).parent.parent / "data" / "dehon_corpus"',
    'BATCH_SIZE       = 100',
    'EMBED_MODEL      = "paraphrase-multilingual-MiniLM-L12-v2"',
    'DOMAIN_PREFIX    = "No contexto da teologia dehoniana e espiritualidade crista"',
    '',
    '# Siglario PT completo - segundo segmento do nome do arquivo = sigla oficial',
    '# Ex: COR-1LD-1864 -> sigla=1LD | INE-ACD-1897 -> sigla=ACD | JRN-NHV-0001 -> sigla=NHV',
    'SIGLARIO_TITLES = {',
    '    "1LD": "Cartas de Padre Dehon",',
    '    "ACD": "Atividade de Padre Dehon",',
    '    "ADP": "Para alem dos Pirineus",',
    '    "APD": "Sobre Padre Dehon",',
    '    "ARP": "Associacao Reparadora",',
    '    "ASC": "O Ano com o Sagrado Coracao de Jesus",',
    '    "CAM": "Coroas de Amor",',
    '    "CFL": "Cadernos Falleur",',
    '    "CHR": "Cronicas do Reino",',
    '    "CON": "Conferencias",',
    '    "CSC": "Catecismo Social",',
    '    "CSJ": "Coracao Sacerdotal de Jesus",',
    '    "DIS": "Discursos",',
    '    "DJU": "Documentos Juridicos",',
    '    "DPS": "Direcoes Politicas e Sociais",',
    '    "DRD": "Discursos, Relatorios, Debates",',
    '    "DSC": "A Devocao ao Sagrado Coracao de Jesus",',
    '    "DSP": "Diretorio Espiritual",',
    '    "DSS": "Documentos para a Santa Se",',
    '    "ECD": "Escritos Duvidosos",',
    '    "ENT": "Arredores",',
    '    "ESC": "Estudos sobre o Sagrado Coracao de Jesus",',
    '    "EXC": "Extratos",',
    '    "EXT": "Artigos Externos",',
    '    "LC1": "Cartas a Padre Dehon",',
    '    "LCC": "Cartas Circulares",',
    '    "MIS": "Missoes",',
    '    "MLA": "Mil Leguas na America do Sul",',
    '    "MMR": "Mes de Maria",',
    '    "MSC": "Mes do Sagrado Coracao de Jesus",',
    '    "MSO": "Manual Social Cristao",',
    '    "NCG": "Nossos Congressos",',
    '    "NHV": "Notas sobre a Historia da minha Vida",',
    '    "NQT": "Notas Quotidianas",',
    '    "NTD": "Notas Diversas",',
    '    "NTO": "Notas sobre a Obra",',
    '    "PDR": "Pequeno Diretorio para os Reitores",',
    '    "PFM": "O Plano da Franco-Maconaria",',
    '    "PRI": "Oracoes",',
    '    "PSC": "Um Sacerdote do Sagrado Coracao de Jesus",',
    '    "PVA": "Prefacio a Vida do Padre Andre",',
    '    "QSS": "Questoes Sociais",',
    '    "RET": "Retiros",',
    '    "REV": "Criticas e Revistas",',
    '    "RMP": "Riqueza, Moderacao ou Pobreza",',
    '    "RSC": "Retiro do Sagrado Coracao",',
    '    "RSO": "Renovacao Social Crista",',
    '    "SAC": "Sicilia, Norte de Africa e Calabria",',
    '    "SMJ": "Irma Maria de Jesus",',
    '    "SVN": "Memorias",',
    '    "THD": "Tese de Doutoramento",',
    '    "THE": "Thesaurus Precum",',
    '    "THL": "Tese para a Licenca",',
    '    "UTP": "A Usura no Tempo Presente",',
    '    "VAM": "Uma Vida de Amor ao Sagrado Coracao de Jesus",',
    '    "VES": "Vida Interior: Exercicios Espirituais",',
    '    "VPR": "Vida Interior: Principios",',
    '    "VYG": "Viagens",',
    '}',
    '',
    'def strip_html(html):',
    '    clean = re.sub(r"<[^>]+>", " ", html or "")',
    '    return re.sub(r"\\s+", " ", clean).strip()',
    '',
    'def extract_sigla(doc_name):',
    '    parts = doc_name.split("-")',
    '    if len(parts) >= 2 and parts[1] in SIGLARIO_TITLES:',
    '        return parts[1]',
    '    return "OUTROS"',
    '',
    'def extract_year(doc_name):',
    '    for p in doc_name.split("-"):',
    '        if re.match(r"^(18|19|20)\\d{2}$", p):',
    '            return p',
    '    return None',
    '',
    'def make_title(doc_name, sigla):',
    '    base = SIGLARIO_TITLES.get(sigla, "Documento (" + sigla + ")")',
    '    year = extract_year(doc_name)',
    '    return (base + " (" + sigla + ") -- " + year) if year else (base + " (" + sigla + ")")',
    '',
    'def get_chunks(filepath):',
    '    try:',
    '        with open(filepath, encoding="utf-8") as f:',
    '            data = json.load(f)',
    '    except Exception as e:',
    '        print("  [ERRO] " + str(filepath.name) + ": " + str(e))',
    '        return []',
    '',
    '    doc_name = data.get("document", filepath.stem)',
    '    sigla    = extract_sigla(doc_name)',
    '    year     = extract_year(doc_name) or ""',
    '    title    = make_title(doc_name, sigla)',
    '    chunks   = []',
    '',
    '    def add(text, para, bible=""):',
    '        t = text.strip()',
    '        if len(t) > 80:',
    '            chunks.append({"text": t[:3000], "doc_name": doc_name, "sigla": sigla,',
    '                           "year": year, "paragraph_num": str(para), "title": title, "bible_refs": bible})',
    '',
    '    def chunk_text(text, base=1):',
    '        step, size = 900, 1200',
    '        for i, s in enumerate(range(0, len(text), step)):',
    '            add(text[s:s+size], base+i)',
    '',
    '    content = data.get("content", {})',
    '    if isinstance(content, dict):',
    '        raw = content.get("text", "") or strip_html(content.get("html", ""))',
    '        inner = content.get("paragraphs", [])',
    '        if inner:',
    '            for i, p in enumerate(inner):',
    '                add(p.get("text", "") or strip_html(p.get("html", "")), i+1)',
    '        elif raw.strip():',
    '            if len(raw.strip()) <= 1500:',
    '                add(raw, 1)',
    '            else:',
    '                chunk_text(raw.strip())',
    '',
    '    root_paras = data.get("paragraphs", [])',
    '    if root_paras and isinstance(root_paras, list):',
    '        s2 = data.get("sigla", sigla)',
    '        t2 = make_title(doc_name, s2)',
    '        for i, p in enumerate(root_paras):',
    '            if isinstance(p, dict):',
    '                pt = p.get("text", "") or strip_html(p.get("html", ""))',
    '                b  = p.get("bible_refs", "") or p.get("biblerefs", "")',
    '            else:',
    '                pt, b = str(p), ""',
    '            if len(pt.strip()) > 80:',
    '                chunks.append({"text": pt.strip()[:3000], "doc_name": doc_name, "sigla": s2,',
    '                               "year": year, "paragraph_num": str(i+1), "title": t2, "bible_refs": b})',
    '',
    '    if not chunks:',
    '        ps = data.get("prosearch", "")',
    '        if isinstance(ps, dict):',
    '            ps = " ".join(str(v) for v in ps.values() if v)',
    '        if isinstance(ps, str) and len(ps.strip()) > 80:',
    '            chunk_text(ps.strip())',
    '',
    '    return chunks',
    '',
    'def main():',
    '    parser = argparse.ArgumentParser()',
    '    parser.add_argument("--limit",  type=int, default=0)',
    '    parser.add_argument("--skip",   type=int, default=0)',
    '    parser.add_argument("--filter", type=str, default="")',
    '    args = parser.parse_args()',
    '',
    '    print("=" * 60)',
    '    print("INGESTAO DO CORPUS DEHONIANO -> PINECONE")',
    '    print("=" * 60)',
    '',
    '    pc    = Pinecone(api_key=PINECONE_API_KEY)',
    '    index = pc.Index(INDEX_NAME)',
    '    print("Vetores no indice: " + str(index.describe_index_stats().total_vector_count))',
    '',
    '    model = SentenceTransformer(EMBED_MODEL)',
    '',
    '    files = sorted(glob.glob(str(CORPUS_DIR / "*.json")))',
    '    if args.filter:',
    '        files = [f for f in files if Path(f).name.startswith(args.filter)]',
    '    if args.skip:',
    '        files = files[args.skip:]',
    '    if args.limit:',
    '        files = files[:args.limit]',
    '    print("Total arquivos: " + str(len(files)))',
    '',
    '    total_chunks = total_up = errors = 0',
    '    batch = []',
    '',
    '    for fi, fp in enumerate(files):',
    '        fname = Path(fp).name',
    '        for ci, c in enumerate(get_chunks(Path(fp))):',
    '            vid = fname.replace(".json", "") + "__" + str(ci)',
    '            batch.append({"id": vid,',
    '                          "te": DOMAIN_PREFIX + ": " + c["text"],',
    '                          "meta": {"text": c["text"], "title": c["title"],',
    '                                   "document_name": c["doc_name"], "sigla": c["sigla"],',
    '                                   "year": c["year"], "paragraph": c["paragraph_num"],',
    '                                   "dehonquote": c["sigla"] + " " + c["paragraph_num"],',
    '                                   "bible_refs": c["bible_refs"]}})',
    '            total_chunks += 1',
    '',
    '            if len(batch) >= BATCH_SIZE:',
    '                try:',
    '                    vecs = model.encode([b["te"] for b in batch], show_progress_bar=False)',
    '                    index.upsert(vectors=[(b["id"], v.tolist(), b["meta"]) for b, v in zip(batch, vecs)])',
    '                    total_up += len(batch)',
    '                    pct = int((fi+1)/len(files)*100)',
    '                    print("[" + str(fi+1) + "/" + str(len(files)) + " " + str(pct) + "%] " + str(total_up) + " vetores | " + fname[:40])',
    '                except Exception as e:',
    '                    print("[ERRO] " + str(e))',
    '                    errors += 1',
    '                batch = []',
    '',
    '        if (fi+1) % 500 == 0:',
    '            time.sleep(0.5)',
    '',
    '    if batch:',
    '        try:',
    '            vecs = model.encode([b["te"] for b in batch], show_progress_bar=False)',
    '            index.upsert(vectors=[(b["id"], v.tolist(), b["meta"]) for b, v in zip(batch, vecs)])',
    '            total_up += len(batch)',
    '        except Exception as e:',
    '            errors += 1',
    '',
    '    time.sleep(2)',
    '    final = index.describe_index_stats().total_vector_count',
    '    print("Concluido. Pinecone: " + str(final) + " vetores")',
    '',
    'if __name__ == "__main__":',
    '    main()',
]

OUT.write_text("\n".join(LINES), encoding="utf-8")
print(f"Arquivo gerado: {OUT}")
print(f"Linhas: {len(LINES)}")
